apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-metadata-app
spec:
  selector:
    matchLabels:
      app: my-metadata-app
  template:
    metadata:
      labels:
        app: my-metadata-app
    spec:
      containers:
      - name: my-metadata-app
        image: luckyganesh/metadata-service:v2
        envFrom:
          - secretRef:
              name: my-metadata-app-secret
          

