apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "my-metadata-service-app"
  labels:
    app: "my-metadata-service-app"

spec:
  selector:
    matchLabels:
      app: "my-metadata-service-app"
  replicas: 3
  template:
    metadata:
      name: my-metadata-service-app
      labels:
        app: "my-metadata-service-app"
    spec:
      containers:
        - name: my-metadata-service-app
          image: luckyganesh/metadata-service:v1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 25
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 25
            timeoutSeconds: 30
  
      curl --header "Content-Type: application/json" \
      --request POST \
      --data '{"group": "groupa", "name":"city", "value": "Pune"}' \
      http://10.244.0.44:8080/metadata