apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  labels:
    type: mongo-db-pv
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 50Mi
  hostPath:
    path: /home/docker/my-local-path
