kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-db-pv-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: mongo-db-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Mi
