version: '2.4'

services:
  my-go-app:
    image:  iaml/golang-docker-app:slim
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s